name: Run Tests with Docker and Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64, arm64]  # Testing on both x86 and ARM

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set Docker platform
      run: |
        echo "Running on ${matrix.architecture} architecture"
        # Set the Docker platform based on the matrix architecture
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker-compose -f docker-compose.yml up -d --build --platform linux/${matrix.architecture}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Create Python Virtual Environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        pip install requests

    - name: Run Tests
      run: |
        source venv/bin/activate
        python testall.py
